FROM php:7.0-apache

#COPY otoja/conf/php.ini /usr/local/etc/php/
COPY otoja/ /var/www/html/

RUN docker-php-source extract \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && docker-php-source delete
