version: '3.1'

services:
  db:
    image: mysql:5.6
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    deploy:
        replicas: 1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lampa22
      MYSQL_DATABASE: osadnicy
    ports:
      - 3306:3306
    volumes:
      - ./mysql_image/uzytkownicy.sql:/docker-entrypoint-initdb.d/dump.sql
      - /var/databases/otoja_mysql:/var/lib/mysql

  php:
    image: otoja:1.0
    ports:
      - 9080:80
      - 9443:443

networks:
  default:
    external:
      name: core
