version: '3.1'

services:
  db:
    image: otoja_mysql:0.2
    deploy:
        replicas: 1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lampa22
      MYSQL_DATABASE: osadnicy
    ports:
      - 3306:3306
  php:
    image: apache:0.4.5
    ports:
      - 80:80
      - 443:443
